version: '3'

services:

      
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  

  # Collector
  otel-collector:
    image: ${OTELCOL_IMG}
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - "./src/otelcollector/otelcol-config.yaml:/etc/otel-collector-config.yaml"
    ports:
     
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"
      

  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongodb:27017/mydatabase
      OTEL_EXPORTER_OTLP_ENDPOINT: otel-collector:4317  # Endpoint of the OpenTelemetry Collector
      OTEL_EXPORTER_PROMETHEUS_ENDPOINT: http://otel-collector:8889/metrics  # Endpoint for Prometheus metrics


  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
