apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: metrics-and-delete-role
rules:
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metrics-and-delete-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: metrics-and-delete-role
  apiGroup: rbac.authorization.k8s.io
