apiVersion: v1
kind: Service
metadata:
  name: cluster-monitor
spec:
  selector:
    app: cluster-monitor
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 5000
  type: NodePort